/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.26 / Jul 2020

Script: COIN Support Command
Author: Whiztler
Script version: 0.92

File: init_sup_command.sqf
**********************************************************************************
DO NOT edit this file. This is part of the COIN mission code base.

Tactical Mission Commander
**********************************************************************************/

#include "init_sup_closeAirSupport.sqf"
#include "init_sup_tankSupport.sqf"
#include "init_sup_airLift.sqf"
#include "init_sup_airDrop.sqf"

if hasInterface then {
	
	_assignCommand = {
		COIN_commandAssigned = true;
		publicVariable "COIN_commandAssigned";
		COIN_leadership = player;
		publicVariableServer "COIN_leadership";
		player setVariable ["COIN_isLeadership", true, 2];

		COIN_leadership call COIN_fnc_assignViper;
		COIN_leadership call COIN_fnc_assignKnight;
		COIN_leadership call COIN_fnc_assignTomcat;
		COIN_leadership call COIN_fnc_assignClipper;
	};	

	// If the CO is not connected/a player then assign to a SQL or FTL
	call {
		if (!COIN_commandAssigned && {(!isNil "BCO_CO") && {player isEqualTo BCO_CO}}) exitWith {player call _assignCommand;};
		sleep 3;
		if COIN_commandAssigned exitWith {};
		if (!COIN_commandAssigned && {(!isNil "BCO_SQL_1") && {player isEqualTo BCO_SQL_1}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_SQL_2") && {player isEqualTo BCO_SQL_2}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_SQL_3") && {player isEqualTo BCO_SQL_3}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_FTL_1") && {player isEqualTo BCO_FTL_1}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_FTL_2") && {player isEqualTo BCO_FTL_2}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_FTL_3") && {player isEqualTo BCO_FTL_3}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_FTL_4") && {player isEqualTo BCO_FTL_4}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_FTL_5") && {player isEqualTo BCO_FTL_5}}) exitWith {player call _assignCommand;};
		if (!COIN_commandAssigned && {(!isNil "BCO_FTL_6") && {player isEqualTo BCO_FTL_6}}) exitWith {player call _assignCommand;};
	};
};

if isServer then {
	[] spawn {
		waitUntil {sleep 0.5; !isNil "COIN_leadership"};
		COIN_leadershipID = owner COIN_leadership;
		diag_log format ["« C O I N »   Support command assigned to: %1 (ID: %2).", COIN_leadership, COIN_leadershipID];
	};	
};