diag_log "ADF rpt: Init - executing: scripts\init_client.sqf"; // Reporting. Do NOT edit/remove
#include "ADF_mod_messageParser.sqf"

player spawn {
	private _bco = [];
	if ADF_mod_RHS then {
		_bco = [
			["BCO_CO","rhsusf_usmc_recon_marpat_d_officer",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_30Rnd_556x45_M855_Stanag",1,30]]],["rhsusf_spc_squadleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],[],"rhsusf_mich_bare_norotos_arc_alt_tan_headset","",["rhsusf_bino_lerca_1200_tan","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RTO_1","rhsusf_usmc_recon_marpat_d_rifleman",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_kac_grip"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_SQL_1","rhsusf_usmc_lar_marpat_d_squadleader",[["rhs_m4_acog_usmc","","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_squadleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhs_mag_m67",2,1],["rhs_mag_an_m8hc",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_m18_green",1,1]]],[],"rhsusf_lwh_helmet_marpatd_headset","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_1","rhsusf_usmc_recon_marpat_d_teamleader",[["rhs_m4a1_m203_acog3_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_teamleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_alt_tan_headset","rhs_googles_black",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_2","rhsusf_usmc_recon_marpat_d_teamleader",[["rhs_m4a1_m203_acog3_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_teamleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_alt_tan_headset","rhs_ess_black",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AR_1","rhsusf_usmc_recon_marpat_d_autorifleman",[["rhs_weap_m27iar","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_iar",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M441_HE",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1]]],"rhsusf_mich_bare_norotos_tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_1","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_2","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_R_1","rhsusf_usmc_recon_marpat_d_rifleman",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_kac_grip"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_1","rhsusf_usmc_recon_marpat_d_machinegunner_m249",[["rhs_weap_m249_pip_S_para_vfg3","","","rhsusf_acc_ACOG2_USMC",["rhsusf_100Rnd_556x45_M855_soft_pouch",100],[],"rhsusf_acc_kac_grip_saw_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhsusf_100Rnd_556x45_M855_soft_pouch",2,100],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhs_mag_mk3a2",2,1]]],["rhsusf_pack_slackman_m249",[["FirstAidKit",2],["rhsusf_100Rnd_556x45_M855_soft_pouch",4,100],["rhs_mag_30Rnd_556x45_M855_Stanag",3,30],["ClaymoreDirectionalMine_Remote_Mag",2,1],["rhs_mag_mk84",4,1],["Chemlight_red",2,1],["Chemlight_green",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AR_2","rhsusf_usmc_recon_marpat_d_autorifleman",[["rhs_weap_m27iar_bipod_acog_usmc_sup_tan","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_iar",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_tan","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_3","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_4","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_R_2","rhsusf_usmc_recon_marpat_d_rifleman",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_kac_grip"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_2","rhsusf_usmc_recon_marpat_d_machinegunner_m249",[["rhs_weap_m249_pip_S_para_vfg3","","","rhsusf_acc_ACOG2_USMC",["rhsusf_100Rnd_556x45_M855_soft_pouch",100],[],"rhsusf_acc_kac_grip_saw_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhsusf_100Rnd_556x45_M855_soft_pouch",2,100],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhs_mag_mk3a2",2,1]]],["rhsusf_pack_slackman_m249",[["FirstAidKit",2],["rhsusf_100Rnd_556x45_M855_soft_pouch",4,100],["rhs_mag_30Rnd_556x45_M855_Stanag",3,30],["ClaymoreDirectionalMine_Remote_Mag",2,1],["rhs_mag_mk84",4,1],["Chemlight_red",2,1],["Chemlight_green",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CLS_1","rhsusf_navy_sarc_d",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",1,30]]],["rhsusf_spc_corpsman",[["rhs_mag_30Rnd_556x45_Mk318_Stanag",6,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_mk3a2",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_an_m8hc",1,1]]],["rhsusf_falconii_sarc",[["Medikit",1],["FirstAidKit",6],["Chemlight_red",1,1]]],"rhsusf_mich_bare_norotos_tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_SQL_2","rhsusf_usmc_lar_marpat_d_squadleader",[["rhs_m4_acog_usmc","","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_squadleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhs_mag_m67",2,1],["rhs_mag_an_m8hc",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_m18_green",1,1]]],[],"rhsusf_lwh_helmet_marpatd_headset","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_3","rhsusf_usmc_recon_marpat_d_teamleader",[["rhs_m4a1_m203_acog3_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_teamleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_alt_tan_headset","rhs_googles_clear",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_4","rhsusf_usmc_recon_marpat_d_teamleader",[["rhs_m4a1_m203_acog3_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_teamleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_alt_tan_headset","rhs_googles_clear",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AR_3","rhsusf_usmc_recon_marpat_d_autorifleman",[["rhs_weap_m27iar_bipod_acog_usmc_sup_tan","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_iar",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_5","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_black",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_6","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_R_3","rhsusf_usmc_recon_marpat_d_rifleman",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_kac_grip"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_3","rhsusf_usmc_recon_marpat_d_machinegunner_m249",[["rhs_weap_m249_pip_S_para_vfg3","","","rhsusf_acc_ACOG2_USMC",["rhsusf_100Rnd_556x45_M855_soft_pouch",100],[],"rhsusf_acc_kac_grip_saw_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhsusf_100Rnd_556x45_M855_soft_pouch",2,100],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhs_mag_mk3a2",2,1]]],["rhsusf_pack_slackman_m249",[["FirstAidKit",2],["rhsusf_100Rnd_556x45_M855_soft_pouch",4,100],["rhs_mag_30Rnd_556x45_M855_Stanag",3,30],["ClaymoreDirectionalMine_Remote_Mag",2,1],["rhs_mag_mk84",4,1],["Chemlight_red",2,1],["Chemlight_green",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AR_4","rhsusf_usmc_recon_marpat_d_autorifleman",[["rhs_weap_m27iar_bipod_acog_usmc_sup_tan","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_iar",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_7","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_8","rhsusf_usmc_recon_marpat_d_rifleman_at",[["rhs_m4a1_acog2_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG2_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_R_4","rhsusf_usmc_recon_marpat_d_rifleman",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],"rhsusf_acc_kac_grip"],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1],["rhs_mag_mk84",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",4,7],["rhs_mag_mk3a2",2,1],["Chemlight_green",1,1]]],[],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_4","rhsusf_usmc_recon_marpat_d_machinegunner_m249",[["rhs_weap_m249_pip_S_para_vfg3","","","rhsusf_acc_ACOG2_USMC",["rhsusf_100Rnd_556x45_M855_soft_pouch",100],[],"rhsusf_acc_kac_grip_saw_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhsusf_100Rnd_556x45_M855_soft_pouch",2,100],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhs_mag_mk3a2",2,1]]],["rhsusf_pack_slackman_m249",[["FirstAidKit",2],["rhsusf_100Rnd_556x45_M855_soft_pouch",4,100],["rhs_mag_30Rnd_556x45_M855_Stanag",3,30],["ClaymoreDirectionalMine_Remote_Mag",2,1],["rhs_mag_mk84",4,1],["Chemlight_red",2,1],["Chemlight_green",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CLS_2","rhsusf_navy_sarc_d",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",1,30]]],["rhsusf_spc_corpsman",[["rhs_mag_30Rnd_556x45_Mk318_Stanag",6,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_mk3a2",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_an_m8hc",1,1]]],["rhsusf_falconii_sarc",[["Medikit",1],["FirstAidKit",6],["Chemlight_red",1,1]]],"rhsusf_mich_bare_norotos_tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_SQL_3","rhsusf_usmc_lar_marpat_d_squadleader",[["rhs_m4_acog_usmc","","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_squadleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhs_mag_m67",2,1],["rhs_mag_an_m8hc",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_m18_green",1,1]]],[],"rhsusf_lwh_helmet_marpatd_headset","rhs_googles_black",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CLS_3","rhsusf_navy_sarc_d",[["rhs_weap_m4a1_carryhandle_grip3","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",1,30]]],["rhsusf_spc_corpsman",[["rhs_mag_30Rnd_556x45_Mk318_Stanag",6,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_mk3a2",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_an_m8hc",1,1]]],["rhsusf_falconii_sarc",[["Medikit",1],["FirstAidKit",6],["Chemlight_red",1,1]]],"rhsusf_mich_bare_norotos_tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_5","rhsusf_usmc_recon_marpat_d_teamleader",[["rhs_m4a1_m203_acog3_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_teamleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_falconii_recon",[["FirstAidKit",2],["rhs_mag_M433_HEDP",6,1],["rhs_mag_M585_white",5,1],["rhs_mag_mk84",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_bare_norotos_alt_tan_headset","",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_6","rhsusf_usmc_recon_marpat_d_machinegunner",[["rhs_weap_m240b_usmc","","","rhsusf_acc_ACOG_MDO",["rhsusf_50Rnd_762x51",50],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_mg",[["rhsusf_50Rnd_762x51",3,50],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhs_mag_mk3a2",2,1]]],["rhsusf_pack_slackman_m240",[["rhsusf_50Rnd_762x51",6,50]]],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MM_1","rhsusf_usmc_recon_marpat_d_sniper_M107",[["rhs_weap_M107_d_premier","","","rhsusf_acc_premier",["rhsusf_mag_10Rnd_STD_50BMG_M33",10],[],""],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_marksman",[["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhsusf_mag_10Rnd_STD_50BMG_M33",1,10]]],[],"rhsusf_mich_bare_norotos_arc_tan","rhs_googles_clear",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_5","rhsusf_usmc_recon_marpat_d_machinegunner_m249",[["rhs_weap_m249_pip_S_para_vfg3","","","rhsusf_acc_ACOG2_USMC",["rhsusf_100Rnd_556x45_M855_soft_pouch",100],[],"rhsusf_acc_kac_grip_saw_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_mag_7x45acp_MHP",1,7],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_spc_light",[["rhsusf_100Rnd_556x45_M855_soft_pouch",2,100],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["rhs_mag_mk3a2",2,1]]],["rhsusf_pack_slackman_m249",[["FirstAidKit",2],["rhsusf_100Rnd_556x45_M855_soft_pouch",4,100],["rhs_mag_30Rnd_556x45_M855_Stanag",3,30],["ClaymoreDirectionalMine_Remote_Mag",2,1],["rhs_mag_mk84",4,1],["Chemlight_red",2,1],["Chemlight_green",2,1],["rhs_mag_m18_red",2,1],["rhs_mag_m18_green",2,1],["rhs_mag_m18_purple",2,1],["rhs_mag_m18_yellow",2,1]]],"rhsusf_mich_helmet_marpatd_norotos","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AT_1","rhsusf_usmc_marpat_d_javelin",[["rhs_weap_m16a4_acog_usmc","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_fgm148","","","",["rhs_fgm148_magazine_AT",1],[],""],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhs_mag_m67",1,1]]],[],"rhsusf_lwh_helmet_marpatd","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AAT_1","rhsusf_usmc_marpat_d_javelin_assistant",[["rhs_weap_m16a4_acog_usmc","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],[],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_light",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhs_mag_m67",1,1]]],["rhsusf_assault_eagleaiii_coy_at",[["rhs_fgm148_magazine_AT",1,1]]],"rhsusf_lwh_helmet_marpatd","rhs_googles_clear",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_6","rhsusf_usmc_recon_marpat_d_teamleader",[["rhs_m4a1_m203_acog3_usmc_sup","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],["rhs_weap_fim92","","","",["rhs_fim92_mag",1],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["Chemlight_green",1,1]]],["rhsusf_spc_teamleader",[["rhs_mag_30Rnd_556x45_M855_Stanag",5,30],["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",1,30],["rhsusf_mag_7x45acp_MHP",3,7],["rhs_mag_mk3a2",2,1],["rhs_mag_mk84",1,1],["Chemlight_green",1,1],["Chemlight_red",2,1]]],["rhsusf_assault_eagleaiii_coy_aa",[["rhs_fim92_mag",1,1]]],"rhsusf_mich_bare_norotos_alt_tan_headset","rhs_googles_clear",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CREW_1","rhsusf_usmc_lar_marpat_d_combatcrewman",[["rhs_m4_acog_usmc","","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_crewman",[["rhs_mag_30Rnd_556x45_M855_Stanag",2,30],["rhsusf_mag_15Rnd_9x19_FMJ",3,15],["rhs_mag_m18_red",1,1],["rhs_mag_an_m8hc",1,1]]],[],"rhsusf_cvc_helmet","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CREW_2","rhsusf_usmc_lar_marpat_d_combatcrewman",[["rhs_m4_acog_usmc","","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_crewman",[["rhs_mag_30Rnd_556x45_M855_Stanag",2,30],["rhsusf_mag_15Rnd_9x19_FMJ",3,15],["rhs_mag_m18_red",1,1],["rhs_mag_an_m8hc",1,1]]],[],"rhsusf_cvc_helmet","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CREW_3","rhsusf_usmc_lar_marpat_d_combatcrewman",[["rhs_m4_acog_usmc","","rhsusf_acc_anpeq16a_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_14",1]]],["rhsusf_spc_crewman",[["rhs_mag_30Rnd_556x45_M855_Stanag",2,30],["rhsusf_mag_15Rnd_9x19_FMJ",3,15],["rhs_mag_m18_red",1,1],["rhs_mag_an_m8hc",1,1]]],[],"rhsusf_cvc_helmet","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["pHawkPilot","rhsusf_usmc_marpat_d_helipilot",[["rhs_weap_m4_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_15",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["rhsusf_spc_crewman",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_m18_red",1,1]]],[],"rhsusf_hgu56p","rhs_googles_clear",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["pHawkGunner","rhsusf_usmc_marpat_d_helipilot",[["rhs_weap_m4_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_FROG01_d",[["FirstAidKit",1],["rhsusf_ANPVS_15",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["rhsusf_spc_crewman",[["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_m18_red",1,1]]],[],"rhsusf_hgu56p","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]]
		];
	};
	if ADF_mod_CFP then {
		_bco = [
			["BCO_RTO_1","CUP_B_FR_Soldier_Assault_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USMC_FROG3_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_7Rnd_45ACP_1911",2,7]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CO","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CLS_1","CUP_B_FR_Medic_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG1_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_Corpsman",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_B_USMC_AssaultPack_Medic",[["Medikit",1],["FirstAidKit",10]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_1","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_2","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_SQL_1","CUP_B_USMC_Soldier_SL_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_M9","","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_AR_1","CFP_B_USMC_Automatic_Rifleman_DES_01",[["CUP_lmg_M249","","","",["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",200],[],""],[],[],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1]]],["CUP_V_B_MTV_MG",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",2,200]]],["CUP_B_USMC_MOLLE_AR",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",3,200]]],"CUP_H_USMC_LWH_ESS_DES","G_Squares_Tinted",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AR_2","CFP_B_USMC_Automatic_Rifleman_DES_01",[["CUP_lmg_M249","","","",["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",200],[],""],[],[],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1]]],["CUP_V_B_MTV_MG",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",2,200]]],["CUP_B_USMC_MOLLE_AR",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",3,200]]],"CUP_H_USMC_LWH_ESS_DES","G_Shades_Red",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_1","CUP_B_FR_Soldier_AR_DES",[["CUP_lmg_Mk48_des_Aim_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_CompM2_low_coyote",[],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_V_B_Eagle_SPC_MG",[]],["CUP_B_FR_MOLLE_MG",[["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",4,100]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_2","CUP_B_FR_Soldier_AR_DES",[["CUP_lmg_Mk48_des_Aim_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_CompM2_low_coyote",[],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_V_B_Eagle_SPC_MG",[]],["CUP_B_FR_MOLLE_MG",[["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",4,100]]],"CUP_H_USMC_LWH_ESS_DES","G_Shades_Black",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_1","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_RAT_2","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_RAT_3","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_RAT_4","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_R_1","CUP_B_FR_Soldier_Assault_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USMC_FROG3_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_7Rnd_45ACP_1911",2,7]]],[],"CUP_H_USMC_LWH_ESS_DES","G_Aviator",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_R_2","CUP_B_FR_Soldier_Assault_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USMC_FROG3_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_7Rnd_45ACP_1911",2,7]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CLS_2","CUP_B_FR_Medic_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG1_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_Corpsman",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_B_USMC_AssaultPack_Medic",[["Medikit",1],["FirstAidKit",10]]],"CUP_H_USMC_LWH_ESS_DES","G_Shades_Green",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_3","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_4","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_SQL_2","CUP_B_USMC_Soldier_SL_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_M9","","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_AR_3","CFP_B_USMC_Automatic_Rifleman_DES_01",[["CUP_lmg_M249","","","",["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",200],[],""],[],[],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1]]],["CUP_V_B_MTV_MG",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",2,200]]],["CUP_B_USMC_MOLLE_AR",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",3,200]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_AR_4","CFP_B_USMC_Automatic_Rifleman_DES_01",[["CUP_lmg_M249","","","",["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",200],[],""],[],[],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1]]],["CUP_V_B_MTV_MG",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",2,200]]],["CUP_B_USMC_MOLLE_AR",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",3,200]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_3","CUP_B_FR_Soldier_AR_DES",[["CUP_lmg_Mk48_des_Aim_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_CompM2_low_coyote",[],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_V_B_Eagle_SPC_MG",[]],["CUP_B_FR_MOLLE_MG",[["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",4,100]]],"CUP_H_USMC_LWH_ESS_DES","G_Shades_Red",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_4","CUP_B_FR_Soldier_AR_DES",[["CUP_lmg_Mk48_des_Aim_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_CompM2_low_coyote",[],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_V_B_Eagle_SPC_MG",[]],["CUP_B_FR_MOLLE_MG",[["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",4,100]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_RAT_5","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_RAT_6","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_RAT_7","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_RAT_8","CUP_B_USMC_Soldier_LAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_M136","","","",[],[],""],[],["CUP_U_B_USMC_FROG3_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_R_3","CUP_B_FR_Soldier_Assault_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USMC_FROG3_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_7Rnd_45ACP_1911",2,7]]],[],"CUP_H_USMC_LWH_ESS_DES","G_Shades_Black",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_R_4","CUP_B_FR_Soldier_Assault_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USMC_FROG3_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_7Rnd_45ACP_1911",2,7]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MM_1","B_Sharpshooter_F",[["srifle_DMR_03_tan_AMS_LP_F","","acc_pointer_IR","optic_AMS_snd",["20Rnd_762x51_Mag",20],[],"bipod_01_F_snd"],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",1],["20Rnd_762x51_Mag",1,20],["Chemlight_green",1,1]]],["V_PlateCarrier1_rgr",[["20Rnd_762x51_Mag",6,20],["16Rnd_9x21_Mag",2,16],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1],["HandGrenade",2,1]]],[],"H_HelmetB","G_Combat",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]], 
			["BCO_CLS_3","CUP_B_FR_Medic_DES",[["CUP_arifle_M4A1_Aim","","","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG1_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_Corpsman",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_B_USMC_AssaultPack_Medic",[["Medikit",1],["FirstAidKit",10]]],"CUP_H_USMC_LWH_ESS_DES","G_Squares",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_5","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_FTL_6","CUP_B_FR_Soldier_TL_DES",[["CUP_arifle_M4A3_desert_GL_ACOG_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_RCO_desert",["CUP_30Rnd_556x45_Stanag",30],["CUP_FlareWhite_M203",1],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1]]],["CUP_V_B_Eagle_SPC_Scout",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_FlareWhite_M203",1,1],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_SQL_3","CUP_B_USMC_Soldier_SL_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_M9","","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_Eagle_SPC_SL",[["CUP_30Rnd_556x45_Stanag",1,30],["CUP_15Rnd_9x19_M9",2,15]]],[],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_AAT_1","CUP_B_USMC_Soldier_HAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_Javelin","","","",["CUP_Javelin_M",1],[],""],[],["CUP_U_B_USMC_FROG2_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","G_Aviator",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_AT_1","CUP_B_USMC_Soldier_HAT_FROG_DES",[["CUP_arifle_M16A4_Aim_Laser","","CUP_acc_ANPEQ_2","CUP_optic_CompM2_low",["CUP_30Rnd_556x45_Stanag",30],[],""],["CUP_launch_Javelin","","","",["CUP_Javelin_M",1],[],""],[],["CUP_U_B_USMC_FROG2_DMARPAT",[["CUP_30Rnd_556x45_Stanag",2,30]]],["CUP_V_B_Eagle_SPC_AT",[]],[],"CUP_H_USMC_LWH_ESS_DES","G_Shades_Green",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS14"]]], 
			["BCO_MG_5","CUP_B_FR_Soldier_AR_DES",[["CUP_lmg_Mk48_des_Aim_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_CompM2_low_coyote",[],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_V_B_Eagle_SPC_MG",[]],["CUP_B_FR_MOLLE_MG",[["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",4,100]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_MG_6","CUP_B_FR_Soldier_AR_DES",[["CUP_lmg_Mk48_des_Aim_Laser","","CUP_acc_ANPEQ_2_desert","CUP_optic_CompM2_low_coyote",[],[],""],[],["CUP_hgun_M9_snds","CUP_muzzle_snds_M9","","",["CUP_15Rnd_9x19_M9",15],[],""],["CUP_U_B_USMC_FROG2_DMARPAT",[["FirstAidKit",1],["CUP_15Rnd_9x19_M9",2,15]]],["CUP_V_B_Eagle_SPC_MG",[]],["CUP_B_FR_MOLLE_MG",[["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",4,100]]],"CUP_H_USMC_LWH_ESS_DES","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CREW_3","CFP_B_USMC_Crewman_DES_01",[["CUP_arifle_M4A1","","","",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",2,30],["CUP_7Rnd_45ACP_1911",1,7]]],["CUP_V_B_MTV",[["CUP_7Rnd_45ACP_1911",1,7]]],[],"H_HelmetCrew_I","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CREW_1","CFP_B_USMC_Crewman_DES_01",[["CUP_arifle_M4A1","","","",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",2,30],["CUP_7Rnd_45ACP_1911",1,7]]],["CUP_V_B_MTV",[["CUP_7Rnd_45ACP_1911",1,7]]],[],"H_HelmetCrew_I","G_Shades_Green",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["BCO_CREW_2","CFP_B_USMC_Crewman_DES_01",[["CUP_arifle_M4A1","","","",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CFP_U_FieldUniform_marpat_d",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",2,30],["CUP_7Rnd_45ACP_1911",1,7]]],["CUP_V_B_MTV",[["CUP_7Rnd_45ACP_1911",1,7]]],[],"H_HelmetCrew_I","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]], 
			["pHawkPilot","CFP_B_USARMY_2003_Pilot_DES_01",[["CUP_arifle_M4A1","","","",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USArmy_PilotOverall",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_PilotVest",[["CUP_7Rnd_45ACP_1911",1,7]]],[],"CUP_H_USMC_Helmet_Pilot","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS7"]]], 
			["pHawkGunner","CFP_B_USARMY_2003_Pilot_WDL_01",[["CUP_arifle_M4A1","","","",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["CUP_U_B_USArmy_PilotOverall",[["FirstAidKit",1],["CUP_30Rnd_556x45_Stanag",1,30]]],["CUP_V_B_PilotVest",[["CUP_7Rnd_45ACP_1911",1,7]]],[],"CUP_H_USMC_Helmet_Pilot","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS7"]]]
		];
	};
	
	{
		if (vehicleVarName player == _x # 0) exitWith {
			player setUnitLoadout _x # 2;
			COIN_loadout = _x # 2;
		};
	} forEach _bco;
};

[] spawn {
	waitUntil {time > 50};
	player allowDamage false;
	player setPosATL ([teleportFlagPole, 32] call ADF_fnc_randomPosMax);
	// Hawk
	if (!isNil "pHawkPilot" && {player == pHawkPilot}) then {COIN_infPatch = false;};
	if (!isNil "pHawkGunner" && {player == pHawkGunner}) then {COIN_infPatch = false;};
	diag_log format ["« C O I N »  Player (%1) assigned. Game duration: %2", name player, [(round time)] call BIS_fnc_secondsToString];
	sleep 1;
	player allowDamage true;
};

ADF_fnc_endMission= {
	["CMD","BCO",localize "STR_ADF_clientInit_EndMission"] call ADF_fnc_MessageParser; sleep 20;
	
	_l = ["tLayer"] call BIS_fnc_rscLayer; 
	_l cutText ["", "BLACK", 20];
	["<img size= '10' shadow='false' image='mission\images\intro_coin.paa'/><br/><br/><t size='.7' color='#FFFFFF'>COIN | Counter Insurgency Operations</t>",0,0,9,8] spawn BIS_fnc_dynamicText;		
	['END1', true, 22] call BIS_fnc_endMission;
};

COIN_fnc_announceAO = {
	// init
	params [
		["_ao_marker", "", [""]],
		["_opforSpawned", 0, [0]],
		["_winCondition", 0, [0]],
		["_ao_name", "", [""]]
	];
	private _ao_size = ((markerSize _ao_marker) select 0);

	private _logTime = [dayTime] call BIS_fnc_timeToString;
	private _logTimeText = "Log: " + _logTime;
	private _logMessage = format [localize "STR_ADF_clientInit_AnnounceAOlog", _logTime, _ao_name, _ao_size, _opforSpawned, _winCondition];
	player createDiaryRecord ["COIN Log", [_logTimeText, _logMessage]];
	
	[_ao_name, _ao_size, _opforSpawned, _winCondition] spawn {
		params ["_ao_name", "_ao_size", "_opforSpawned", "_winCondition"];
		for "_i" from 1 to 30 do {
			hint parseText format [localize "STR_ADF_clientInit_AnnounceAOhint", _ao_name, _ao_size, _opforSpawned, _winCondition];
			uiSleep 1;
		};
	};
};

COIN_fnc_intelFound = {
	if COIN_intelFoundActive exitWith {};	
	params ["_object", "_caller", "_intelFound", "_messageID"];
	sleep 10;
	[_object, _caller, _intelFound, _messageID] remoteExec ["COIN_fnc_intelFoundServer", 2];	
};

COIN_fnc_intelFoundMsg = {
	params [
		"_intelType",
		"_intelDesc"
	];
	call {
		if (_intelType == 1) exitWith {_intelDesc = localize "STR_ADF_intelFoundMsg_type1"};
		if (_intelType == 2) exitWith {_intelDesc = localize "STR_ADF_intelFoundMsg_type2"};
		if (_intelType == 3) exitWith {_intelDesc = localize "STR_ADF_intelFoundMsg_type3"};
	};
	["CMD", "BCO", format [localize "STR_ADF_intelFoundMsg_hint", _intelDesc]] call ADF_fnc_MessageParser;

};

COIN_fnc_clearedAO = {
	// init
	params [
		["_ao_name", "", [""]],
		["_duration", "", [""]],
		["_ao_currentNr", 0, [0]]
	];
	private _logTime = [dayTime] call BIS_fnc_timeToString;
	private _logTimeText = "Log: " + _logTime;
	private _logMessage = format [localize "STR_ADF_clientInit_clearedAOlog", _logTime, _ao_name, _duration, COIN_totalAOs - _ao_currentNr];
	player createDiaryRecord ["COIN Log", [_logTimeText, _logMessage]];
	
	if (_ao_currentNr == COIN_totalAOs) then {
		private _layer = ["tLayer"] call BIS_fnc_rscLayer; 
		_layer cutText ["", "BLACK", 20];
		["<img size= '11' shadow='false' image='mission\images\intro_COIN.paa'/><br/><t size='2' color='#FFFFFF'>V I C T O R Y</t>",0,0,9,8] spawn BIS_fnc_dynamicText;		
		['END1', true, 22] call BIS_fnc_endMission;
	} else {
		for "_i" from 1 to 30 do {
			hint parseText format [localize "STR_ADF_clientInit_clearedAOhint", _ao_name, _duration, COIN_totalAOs - _ao_currentNr];
			uiSleep 1;
		};
	};
};

diag_log format ["« C O I N »   Client functions loaded. Waiting for ADF_missionInit: %1", ADF_missionInit];
waitUntil {sleep 2; ADF_missionInit};
diag_log format ["« C O I N »   ADF_missionInit: %1. Wrapping up client init.", ADF_missionInit];

if ADF_mod_ACE3 then {[player, currentWeapon player, currentMuzzle player] call ACE_SafeMode_fnc_lockSafety;};

if COIN_infPatch then {
	[player,""] call BIS_fnc_setUnitInsignia;
	[player,"FIRSTRECON"] call BIS_fnc_setUnitInsignia;
} else {
	[player,""] call BIS_fnc_setUnitInsignia;
	[player,"HMLA"] call BIS_fnc_setUnitInsignia;
};
sleep 5;

// Init
private _location = (nearestLocations [getMarkerPos "respawn_west", ["nameCity", "NameCityCapital", "NameVillage", "NameLocal"], 10000]) select 0;
private _distance = round ([_location, "respawn_west"] call ADF_fnc_checkDistance);

// BIS_fnc_locationDescription
[
	["8 JUNE 2011","<t align = 'center' shadow = '1' size = '0.7'>%1</t><br/>"],
	[(toUpperANSI COIN_WorldName),"<t align = 'center' shadow = '1' size = '1.0'>%1</t><br/>"],
	[format [localize "STR_ADF_clientInit_locationtypeWriter", _distance, toUpper (text _location)],"<t align = 'center' shadow = '1' size = '1.0'>%1</t><br/>"]	
] spawn ADF_fnc_typeWriter;

_logTime = [dayTime] call BIS_fnc_timeToString;
_logTimeText = format ["Log: %1", _logTime];
private _content = format [localize "STR_ADF_clientInit_introLog", _logTime, COIN_WorldName, COIN_totalAOs];
player createDiaryRecord ["COIN Log", [_logTimeText, _content]];

private _introHint = "STR_ADF_clientInit_introHint_1"; // AO and Sides
if !COIN_EXEC_sideMissions then {_introHint = "STR_ADF_clientInit_introHint_2"}; // Only AO missions
if !COIN_EXEC_aoMissions then {_introHint = "STR_ADF_clientInit_introHint_3"}; // Only side missions
hint parseText format [localize _introHint, COIN_WorldName, COIN_totalAOs];

