/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.26 / Jul 2020

Script: Altitude Based Fatigue (ABF)
Author: Whiztler
Script version: 1.14

File: ADF_init_abf.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
**********************************************************************************/

// Reporting
diag_log "ADF rpt: Init - executing: ADF_init_abf.sqf";

if !hasInterface exitWith {}; // clients only - double check

// Init
private _level_1 = 1.10 + random 0.05;	// 10%
private _level_2 = 1.20 + random 0.05; // 25%
private _level_3 = 1.40 + random 0.10; // 50%
private _level_4 = 1.60 + random 0.10; // 75
private _level_5 = 2;  // 125
private _pause = 60;	// runs every xx seconds
private _fatigue = [];

player enableFatigue true;
ADF_ABF = true;

_ABF_check = {
	private _fatigue = getFatigue player;
	private _position = getPosASL player;

	[_position # 2, _fatigue]
};

_ABF_set = {
	params [
		"_altitude",
		"_level"		
	];
	
	player setFatigue _altitude * _level;
	if ((getFatigue player) > 1) then {player setFatigue 1};	
	true
};

waitUntil {
	private _current = [] call _ABF_check;

	if !((vehicle player) isKindOf "Air") then {
		call {
			if (_current # 0 > 5000)  exitWith {[_current # 1, _level_5] call _ABF_set};
			if (_current # 0 > 4000)  exitWith {[_current # 1, _level_4] call _ABF_set};
			if (_current # 0 > 3000)  exitWith {[_current # 1, _level_3] call _ABF_set};
			if (_current # 0 > 2000)  exitWith {[_current # 1, _level_2] call _ABF_set};
			if (_current # 0 > 1500)  exitWith {[_current # 1, _level_1] call _ABF_set};
			player setFatigue (_current # 1);	
		};
	};
	
	sleep _pause;
	(!alive player)
};