/*********************************************************************************
 _____ ____  _____ 
|  _  |    \|   __|
|     |  |  |   __|
|__|__|____/|__|   
ARMA Mission Development Framework
ADF version: 2.26 / Jul 2020

Script: Mission init / Init reporting
Author: Whiztler
Script version: 1.27

File: ADF_init_rpt.sqf
**********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  '\mission\'  folder.
*********************************************************************************/

// Reporting
diag_log "ADF rpt: Init - executing: ADF_init_rpt.sqf";

// Init
private _addons	= "";
private _hc = count (entities "HeadlessClient_F");
private _ai = (count (allUnits - allPlayers)) - _hc;
if (_ai < 0) then {_ai = 0};

// Report included mods supported by ADF
if ADF_mod_CBA then {_addons = _addons + "CBA A3"};
if ADF_mod_ACRE then {_addons = _addons + ", ACRE2"};
if ADF_mod_TFAR then {_addons = _addons + ", TFAR"};
if ADF_mod_CTAB then {_addons = _addons + ", cTab"};
if ADF_mod_ACE3 then {_addons = _addons + ", ACE3"};
if ADF_mod_Ares then {_addons = _addons + ", Ares/Achilles"};
if ADF_mod_CSAT then {_addons = _addons + ", TEC CSAT"};
if ADF_mod_RHS then {_addons = _addons + ", RHS"};
if ADF_mod_PROPFOR then {_addons = _addons + ", Project Opfor"};
if ADF_mod_3CB_FACT then {_addons = _addons + ", 3CB Factions"};
if ADF_mod_JR then {_addons = _addons + ", ASDG JR"};
if ADF_mod_NIARMS then {_addons = _addons + ", NIarms"};
if (ADF_mod_CUP_T || ADF_mod_AIA) then {_addons = _addons + ", CUP Terrains"};
if ADF_mod_CUP_W then {_addons = _addons + ", CUP Weapons"};
if ADF_mod_CUP_U then {_addons = _addons + ", CUP Units"};
if ADF_mod_CUP_V then {_addons = _addons + ", CUP Vehicles"};
if ADF_mod_CFP then {_addons = _addons + ", Community Factions Project"};
if ADF_mod_ASRAI then {_addons = _addons + ", ASR AI"};
if ADF_mod_VCOMAI then {_addons = _addons + ", vCom AI"};
if ADF_mod_BCOMBAT then {_addons = _addons + ", bCombat"};
if ADF_mod_BAI then {_addons = _addons + ", Charlie Foxtrot better AI"};
if ADF_mod_DANGER then {_addons = _addons + ", LAMBS Danger.fsm"};

// Init reporting
if ADF_debug then {
	diag_log "";
	diag_log "______________________________________________________________________________________";
	diag_log "";
	_msg = format ["Init - ADF version: %1",ADF_tpl_version];
	[_msg, false] call ADF_fnc_log;
	_msg = format ["Init - Mission version: %1",ADF_mission_version];
	[_msg, false] call ADF_fnc_log;
	_msg = format ["Init - Number of players connected: %1", count allPlayers];
	[_msg, false] call ADF_fnc_log;
	_msg = format ["Init - Number of HC's connected: %1", _hc];
	[_msg, false] call ADF_fnc_log;	
	_msg = format ["Init - Number of AI's active: %1", _ai];
	[_msg, false] call ADF_fnc_log;
	diag_log "______________________________________________________________________________________";
	diag_log "";
} else { // Live mission logging
	diag_log "";
	diag_log "______________________________________________________________________________________";
	diag_log "";
	diag_log format ["ADF rpt: Init - ADF version: %1", ADF_tpl_version];
	diag_log format ["ADF rpt: Init - Mission version: %1", ADF_mission_version];
	diag_log format ["ADF rpt: Init - Mission name: %1", (getText (missionConfigFile >> "overviewText"))];
	diag_log format ["ADF rpt: Init - Mission developer: %1", (getText (missionConfigFile >> "author"))];
	diag_log "──────────────────────────────────────────────────────────────────────────────────────";
	diag_log format ["ADF rpt: Init - Number of players connected: %1", (count allPlayers) - _hc];
	diag_log format ["ADF rpt: Init - Number of HC's connected: %1", _hc];
	diag_log format ["ADF rpt: Init - Number of AI's active: %1", _ai];
	diag_log "──────────────────────────────────────────────────────────────────────────────────────";
	diag_log format ["ADF rpt: Init - ADF supported addons detected: %1", _addons];
	diag_log "──────────────────────────────────────────────────────────────────────────────────────";
	diag_log "ADF_debug mode is disabled (set to 'disable') in the mission params. To debug missions";
	diag_log "enable 'Mission Debug' in the in mission parameters during slotting in.";
	diag_log "______________________________________________________________________________________";
	diag_log "";
};

// Server FPS reporting in RPT. The frequency of the reporting is based on server performance.
if ADF_extRpt then {[60, "Server", "Server"] spawn ADF_fnc_statsReporting};